### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by 008chen** [weexteam/weex-vue-render#39]
(node:2784) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '\u0000commonjs-proxy:F:\\code\\vue-render-for-apache-weex-1.0.35\\vue-render-for-apache-weex-1.0.35\\node_modules\\core-js\\mod...
    at Object.readFile (fs.js:297:3)
    at next (F:\code\vue-render-for-apache-weex-1.0.35\vue-render-for-apache-weex-1.0.35\node_modules\browser-resolve\index.js:98:12)
    at load_shims (F:\code\vue-render-for-apache-weex-1.0.35\vue-render-for-apache-weex-1.0.35\node_modules\browser-resolve\index.js:116:7)
    at resolve (F:\code\vue-render-for-apache-weex-1.0.35\vue-render-for-apache-weex-1.0.35\node_modules\browser-resolve\index.js:236:5)
    at F:\code\vue-render-for-apache-weex-1.0.35\vue-render-for-apache-weex-1.0.35\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:66:5
    at new Promise (<anonymous>)
    at resolveId$1 (F:\code\vue-render-for-apache-weex-1.0.35\vue-render-for-apache-weex-1.0.35\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:63:11)
    at promise.then.result (F:\code\vue-render-for-apache-weex-1.0.35\vue-render-for-apache-weex-1.0.35\node_modules\rollup\dist\rollup.js:1735:32)
(node:2784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by felixxxp** [comment]
用8.x的node 版本试下，我切到8.17.0，报错没有了
